name: "Feature"

on:
  push:
    branches:
      - 'feature**'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash
        working-directory: app
    steps:
      - name: actions/checkout
        uses: actions/checkout@v4

  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash
        working-directory: app
    steps:
      - name: actions/checkout
        uses: actions/checkout@v4

  package:
    needs:
      - build
      - test
    name: package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash
        working-directory: app
    steps:
      - name: actions/checkout
        uses: actions/checkout@v4        

  deploy:
    needs:
      - package
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash
        working-directory: app
    steps:
      - name: actions/checkout
        uses: actions/checkout@v4          